builds:
  - main: ./cmd/terramate-lsp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows (when we add win support)

archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: win (when we add win support)
      386: i386
      amd64: x86_64

dockers:
  - dockerfile: hack/release/Dockerfile
    image_templates:
      - "ghcr.io/mineiros-io/{{.ProjectName}}:latest"
      - "ghcr.io/mineiros-io/{{.ProjectName}}:{{.Version}}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^spec:'
      - '^test:'
      - '^tests:'
      - '^testing:'
      - '^refactor:'
      - '^chore:'
